/** @type {import('tailwindcss').Config} */
const url = require("url");
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    fontFamily: {
      poppins: ["Poppins", "sans-serif"],
    },
    extend: {
      colors: {
        text: "#6b7280",
        title: "#111827",
        validateText: "#dc2626",
        textGrayDark: "#4b5563",
        textGrayLight: "#9ca3af",
        link: "#4f46e5",
        background: "#f3f4f6",
        pageBg: "#f9fafb",
        boxBg: "#ffffff",
        boxBorder: "#e5e7eb",
        boxBorderTop: "#fbbf24",
        border: "#e5e7eb",
        inputBg: "#00000000",
        inputText: "#111827",
        inputBorder: "#d1d5db",
        inputHighlight: "#4f46e5",
        primaryButtonBg: "#4f46e5",
        primaryButtonBgHover: "#4338ca",
        primaryButtonText: "#ffffff",
        primaryButtonBorder: "#4f46e5",
        secondButtonBg: "#ffffff",
        secondButtonBgHover: "#f9fafb",
        secondButtonText: "#6b7280",
        secondButtonBorder: "#d1d5db",
        imageIconPollBg: "#3b82f6",
        meetingIconPollBg: "#eab308",
        multipleChoiceIconPollBg: "#22c55e",
        liveText: "#166534",
        liveBg: "#dcfce7",
        liveIcon: "#22c55e",
        closeText: "#991b1b",
        closeBg: "#fee2e2",
        closeIcon: "#ef4444",
        draftText: "#854d0e",
        draftBg: "#fef9c3",
        draftIcon: "#eab308",
      },
      backgroundImage: {
        "select-icon": "url('../src/assets/svg/caret-down.svg')",
      },
    },
  },
  plugins: [],
};
